name: 'Renovate Bot GitHub Action'
description: 'GitHub Action to run self-hosted Renovate.'
author: 'Jeroen de Bruijn'
branding:
  icon: refresh-cw
  color: blue
inputs:
  configurationFile:
    description: |
      Configuration file to configure Renovate. Either use this input or the
      'RENOVATE_CONFIG_FILE' environment variable.
    required: false
  token:
    description: |
      GitHub personal access token that Renovate should use. This should be
      configured using a Secret. Either use this input or the 'RENOVATE_TOKEN'
      environment variable.
    required: false
  useSlim:
    description: |
      Deprecated. Add `slim` to `renovate-version` instead.
    required: false
  env-regex:
    description: |
      Override the environment variables which will be passsed into the renovate container.
      Defaults to `^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|(?:HTTPS?|NO)_PROXY|(?:https?|no)_proxy)$`
    required: false
  renovate-version:
    description: |
      Renovate version to use. Defaults to `slim`.
    required: false
  renovate-image:
    description: |
      Renovate docker image name.
      Defaults to `ghcr.io/renovate/renovate`.
    required: false
runs:
  using: node16
  main: dist/index.js
